### ISSUE TITLE
`HasError<T>` can throw, when I would expect `false`

### ISSUE THREAD

**Issue by A9G-Data-Droid** [altmann/FluentResults#204]
ISSUE:
When checking for the existence of a custom `IError` I sometimes get an exception that does not clearly point to the problem:

> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at FluentResults.ResultHelper.HasError[TError](List`1 errors, Func`2 predicate, IEnumerable`1& result)
   at FluentResults.ResultHelper.HasError[TError](List`1 errors, Func`2 predicate, IEnumerable`1& result)
   at FluentResults.ResultBase.HasError[TError](Func`2 predicate, IEnumerable`1& result)
   at FluentResults.ResultBase.HasError[TError](IEnumerable`1& result)
   at FluentResults.ResultBase.HasError[TError]()

EXPECTED BEHAVIOR:
I would expect `HasError<T>` to return `false` instead of throwing.

CAUSE:
In my custom error I did not initialize `Reasons` in some cases.

SOLUTION:
I would recommend turning on [`<nullable>enable</nullable>`](https://learn.microsoft.com/en-us/dotnet/csharp/nullable-migration-strategies) to help flag null problems across the code base.

The problem seems to be in [[public static bool HasError<TError>(](https://github.com/altmann/FluentResults/blob/8b675de7e8b6e4c0921e95138c99e15fd52cde40/src/FluentResults/Factories/ResultHelper.cs#L29)](https://github.com/altmann/FluentResults/blob/8b675de7e8b6e4c0921e95138c99e15fd52cde40/src/FluentResults/Factories/ResultHelper.cs#L35)

where `predicate` is null when looking at a null set of `Reasons`.

Adding
```
if(predicate is null) return false
```

is an example fix.

**Comment by altmann** [comment]
Implemented with [v3.16](https://www.nuget.org/packages/FluentResults/3.16.0)
